### ISSUE TITLE
Bug: URL href having <b> tag while using toHTML Function.

### ISSUE THREAD

**Issue by kashyapndps00** [telegraf/entity#2]
When I convert this using toHTML function,
`**👉 Link :- https://example.com**`

In HTML I get,
`<b>👉 Link :- </b><a href="<b>https://example.com</b>"><b>https://example.com</b></a>`

I am getting <b> in URL's href. This seems like a bug.

**Comment by MKRhere** [comment]
Thanks, I discovered other bugs while investigating this one; this version should be much more reliable.
