### ISSUE TITLE
support for new blockquote entity?

### ISSUE THREAD

**Issue by FeiFanLiang** [telegraf/entity#4]
The latest version of Telegram Bot api is already supported

**Comment by MKRhere** [comment]
Related to work on https://github.com/telegraf/types/tree/feat/api-7.0 and https://github.com/telegraf/telegraf/tree/feat/api-7.0
Related to https://github.com/telegraf/types/pull/1 and https://github.com/telegraf/telegraf/issues/1923
Will land soon.

**Comment by MKRhere** [comment]
Landed in 0.5.0
